# entrypoint to solana gossip (must be a remote addr)
gossip_entrypoint = "177.177.177.177:8000"

# folder for storing shreds (optional, default = "./shred-store")
storage = "./shred-store"

# Debugging RPC address (optional, default = "127.0.0.1:3000")
rpc_addr = "127.0.0.1:3000"

# gRPC slot stream (optional, default = "127.0.0.1:3001")
grpc_addr = "127.0.0.1:3001"

# optional, fallback to mock metrics if not set
[influxdb]
host = "http://localhost:8181"
database = "test"
token = "xyz"