syntax = "proto3";

import "pb/slot_entry.proto";

package slot_stream;

service SlotStream {
    rpc StreamSlots(SlotStreamRequest) returns (stream SlotResponse);
    rpc CatchupSlots(CatchupRequest) returns (stream SlotResponse);
}

message SlotStreamRequest {}

message CatchupRequest {
    uint64 from_slot_inclusive = 1;
    uint64 to_slot_exclusive = 2;
}

message SlotResponse {
    repeated slot_entry.Entry entries = 1; // JSON encoded entries 
    uint64 slot = 2;
    uint64 parent_slot = 3;
}
